import Link from 'next/link'

import { defaultLanguage, nonDefaultLanguages, useTranslation } from '../_hooks/i18n'
import ToggleLanguageLink from './_components/ToggleLanguageLink'
import translationDef from './translationDef'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export type RootLayoutProps = Readonly<{
  children: React.ReactNode
  params: Readonly<{
    lang: string
  }>
}>

export default async function RootLayout({ children, params }: RootLayoutProps) {
  const { lang } = params
  const { prefixedUrl, changeLanguageUrl, i18n } = await useTranslation({ lang, translationDef })

  return (
    <html lang={params.lang}>
      <body>
        <header>
          Arthur1/nextjs-sg-i18n-playground
          <nav>
            <ul>
              <li>
                <Link href={prefixedUrl('')}>Home</Link>
              </li>
              <li>
                <Link href={prefixedUrl('sample')}>Sample</Link>
              </li>
              <li>
                <ToggleLanguageLink>change language</ToggleLanguageLink>
              </li>
            </ul>
          </nav>
        </header>
        <hr />
        {children}
        <footer>
          <small>&copy; 2023 @Arthur1</small>
        </footer>
      </body>
    </html>
  )
}
